FROM node:22-alpine

WORKDIR /app

RUN corepack enable
ENV CI=true

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --ignore-scripts

COPY . .

# Skip build in development to speed up image creation
# RUN pnpm run build

CMD ["pnpm", "dev"]
