# fetch-milestone.ps1 [-Repo owner/repo] -Number <n>
param([string]$Repo,[Parameter(Mandatory=$true)][int]$Number)
$ErrorActionPreference="Stop"
function Get-Repo{param([string]$Explicit) if($Explicit){return $Explicit};$url=git remote get-url origin 2>$null;if($url -match 'github\.com[:/](.+?)(\.git)?$'){return $Matches[1]};throw "Could not detect repo. Pass -Repo owner/repo explicitly."}
$Repo=Get-Repo -Explicit $Repo
$Base="./.cache/fetched/milestones";$Dir="$Base/milestone-$Number";New-Item -ItemType Directory -Force -Path $Dir|Out-Null;Set-Content -Path "$Base/.gitignore" -Value "*"
New-Item -ItemType Directory -Force -Path "./.cache/fetched/issues" | Out-Null; Set-Content -Path "./.cache/fetched/.gitignore" -Value "*" -Force
New-Item -ItemType Directory -Force -Path "./.cache/fetched/lists" | Out-Null
function Fetch-IssueFull([int]$Num){$issue=gh issue view $Num -R $Repo --json number,title,body,labels,assignees,state,comments|ConvertFrom-Json;$issue.labels=@($issue.labels|ForEach-Object name);$issue.assignees=@($issue.assignees|ForEach-Object login);$issue|ConvertTo-Json -Depth 100|Out-File -Encoding utf8 "$Dir/issue-$Num.json";$subs=gh api "repos/$Repo/issues/$Num/sub_issues" --jq '.[].number' 2>$null;foreach($sub in $subs){Fetch-IssueFull ([int]$sub)}}
$milestone=gh api "repos/$Repo/milestones/$Number"|ConvertFrom-Json;$title=$milestone.title;[pscustomobject]@{number=$milestone.number;title=$milestone.title;description=$milestone.description;state=$milestone.state;due_on=$milestone.due_on;open_issues=$milestone.open_issues;closed_issues=$milestone.closed_issues;creator=$milestone.creator.login}|ConvertTo-Json|Out-File -Encoding utf8 "$Dir/milestone.json";Write-Host "Fetching milestone #$Number '$title' from $Repo ...";$nums=gh issue list -R $Repo --milestone "$title" --state open --json number --jq '.[].number' 2>$null;foreach($n in $nums){Fetch-IssueFull ([int]$n)};$tree=@("# Milestone #$Number`: $title ($Repo)","","## Issues");$files=Get-ChildItem "$Dir/issue-*.json" -ErrorAction SilentlyContinue;foreach($f in $files){$j=Get-Content $f.FullName -Raw|ConvertFrom-Json;$labels=($j.labels)-join ", ";$tree+="- #$($j.number) [$($j.state)] $($j.title) $(if($labels){\"($labels)\"})"};$tree|Out-File -Encoding utf8 "$Dir/tree.md";$prompt=@("You are working on milestone **#$Number $title** in repo **$Repo**.","","Milestone metadata (description, due date, progress): ``$Dir/milestone.json``","","Full issue data (bodies, labels, assignees, comment history) is available as JSON files in ``$Dir/``:");foreach($f in $files){$j=Get-Content $f.FullName -Raw|ConvertFrom-Json;$prompt+="- ``$Dir/issue-$($j.number).json`` � #$($j.number): $($j.title)"};$prompt+="","Read every file above in full before planning. Sub-issue relationships are reflected in each issue`s body (task lists). Work through the issues, respecting dependencies implied by the task lists.";$prompt|Out-File -Encoding utf8 "$Dir/AGENT_PROMPT.md";Write-Host "`n=== Tree ===";Get-Content "$Dir/tree.md" -ErrorAction SilentlyContinue|Write-Host;Write-Host "`nDone. Agent prompt: $Dir/AGENT_PROMPT.md"
